### ISSUE TITLE
Assignment 3 Ready for Grading + Bonus Question

### ISSUE THREAD

**Issue by sage-grey-voorhees** [VIS-2129-F2020/svoorhees-vis#5]
Hello! My Assignment 3 is Ready for Grading. 

https://github.com/VIS-2129-F2020/svoorhees-vis/blob/master/Assignment3_VIS_REAL.Rmd

@bauranov  Thank you for the extra guidance getting the police records to work! I had fun with this assignment! 

Sage

*Quick Question:* 
**RMD vs HTML**
In this issue I linked to the .RMD not the .HTML. I'm currently having trouble knitting the file so I cant commit the html. I will try again in the am, but for the time being, here is the .rmd link

**Clues:** It is telling me I have an error on line 162 (or at 11%) which is where my first ggplot call is. If it works when I run the chunk individually, I'm not sure why it would falter when I knit.  The YAML is identical to my last assignment. 

**Three Theories** 
1. My internet is being slow and I am using the linked address for the KML files. But why would it falter at the plots not the KMLs?

2. This assignment is in the Quant repo folder and not the Vis Repo (Im worried if I move it I mess up the rmd which is submitted). But this doesnt make sense to me why it wouldn't knit?
 
3.  I'm having more weird quirks with R Studio in general? Seems to easy.

**Comment by bauranov** [comment]
Always read the error message, it will tell you what the problem is. You have: *Error: can't add annotation_scale() to a theme object* in line162. That means R is trying to add something, but for some reason, it can't. To add stuff, you need a plus. So maybe you forgot to add a plus at the end of a line, perhaps in line 168? :)

When you fix that, there will be an error in line 338, use "white" instead of light.

**Comment by sage-grey-voorhees** [comment]
Ah, I was looking at the "R Markdown" interface thinking it was the console! Thank you!  

Uploaded the HTML to GitHub: 
https://vis-2129-f2020.github.io/svoorhees-vis/Assignment3_VIS_REAL.html

**Comment by bauranov** [comment]
Congrats on making an extra effort to get and clean outside data. I can see you are experimenting a lot and I fully encourage it. The plots and the code all look great! 

While it's totally fine to try out different data sets, after all the work you put into getting the police data, I was hoping you would connect it to some other data set and create some hypotheses, maybe even draw some conclusions. DO NOT FEEL OBLIGATED TO DO ANY ADDITIONAL WORK, this is far more than required for this assignment, but you might have a research project here. Keep up the good work.
