### ISSUE TITLE
Difficulty with join

### ISSUE THREAD

**Issue by sage-grey-voorhees** [VIS-2129-F2020/svoorhees-vis#8]
Hi! 

So I'm having difficulty using leaflet on this joined dataframe of fire-risk, my understanding is that when I am combining the datasets, it is producing something incompatible with leaflet. 

In the chunk where the dataframes are joined, I get the warning, "no simple feature geometries present: returning a data.frame or tbl_df"

In The error message in the leaflet chunk is, "Error in polygonData.default(data) : Don't know how to get path data from object of class data.frame".  

What I've tried so far: 
You suggested that I flip the order of the joins, but now its having difficulty finding tract_geoid column

Links: 
Assignment: https://github.com/VIS-2129-F2020/svoorhees-vis/blob/master/Raster_Interpolation_Ass.Rmd
Nm_tracts data: https://github.com/VIS-2129-F2020/svoorhees-vis/blob/master/nm_tracts
Fire_Risk_Data: https://github.com/VIS-2129-F2020/svoorhees-vis/blob/master/rc_risk_data

**Comment by sage-grey-voorhees** [comment]
also, some very important content, "https://twitter.com/michaelkosta/status/1324202677979516929?s=20"

**Comment by sage-grey-voorhees** [comment]
Hi, Im still stuck on this. I made some changes, but something odd was happening with my Vis Repo, so I uploaded to the Quant link is here:

https://github.com/SES-5215-F2020/svoorhees-quant/blob/master/Raster_Interpolation_Ass.Rmd

**Comment by bauranov** [comment]
Hi, flip the order of join to fix the "path data" error, and change from tract to GEOID in the select function to fix "tract_geoid not found" error. Left_join doesn't preserve both GEOID and tract_geoid after joining. 

nm_tracts_risk <-nm_tracts %>%
  left_join(rc_risk_data, by =c("GEOID"="tract_geoid")) %>%
  dplyr::select(tract, GEOID, county, risk, rank, geometry)

Don't transform nm_tracts and all the plots should work.

In the last plot, you put
highlightOptions = highlightOptions(fillColor = risk...
That's how we did in ggplot, but adding colors works differently in leaflet. You can see how to do that here:  
https://vis-2129-f2020.github.io/tutorials/Interactive_maps.html

Haha the pain of watching the elections.
